// Card database for the Quantum Riddler deck explorer.
// Anchored to Corkyboyy's WR list from Modern Challenge 64 2026-05-04 (13th).
const CARDS = {
  // === Endgame ===
  "Quantum Riddler": {
    cost: "{3}{U}{U}",
    cmc: 5,
    type: "Creature — Sphinx",
    pt: "4/6",
    text: "Flying. When this creature enters, draw a card. As long as you have one or fewer cards in hand, if you would draw one or more cards, you draw that many cards plus one instead. Warp {1}{U}.",
    set: "EOE",
    color: "U",
    role: "finisher",
    rarity: "mythic",
  },

  // === Removal package ===
  "Erode": {
    cost: "{W}",
    cmc: 1,
    type: "Instant",
    text: "Destroy target creature or planeswalker. Its controller may search their library for a basic land card, put it onto the battlefield tapped, then shuffle.",
    set: "SOS",
    color: "W",
    role: "removal",
  },
  "Path to Exile": {
    cost: "{W}",
    cmc: 1,
    type: "Instant",
    text: "Exile target creature. Its controller may search their library for a basic land card, put that card onto the battlefield tapped, then shuffle.",
    set: "ALA",
    color: "W",
    role: "removal",
  },
  "Galvanic Discharge": {
    cost: "{R}",
    cmc: 1,
    type: "Instant",
    text: "Choose target creature or planeswalker. You get {E}{E}{E}, then you may pay any amount of {E}. Galvanic Discharge deals that much damage to that permanent.",
    set: "MH3",
    color: "R",
    role: "removal",
  },
  "Wrath of the Skies": {
    cost: "{X}{W}{W}",
    cmc: 2, // base; X paid separately
    type: "Sorcery",
    text: "You get X {E}, then you may pay any amount of {E}. Destroy each artifact, creature, and enchantment with mana value less than or equal to the amount of {E} paid this way.",
    set: "MH3",
    color: "W",
    role: "removal",
  },
  "Wrath of God": {
    cost: "{2}{W}{W}",
    cmc: 4,
    type: "Sorcery",
    text: "Destroy all creatures. They can't be regenerated.",
    set: "10E",
    color: "W",
    role: "removal",
  },
  "Solitude": {
    cost: "{4}{W}",
    cmc: 5,
    type: "Creature — Elemental Incarnation",
    pt: "3/2",
    text: "Lifelink. When this creature enters, exile another target creature. Evoke — Exile a white card from your hand.",
    set: "MH2",
    color: "W",
    role: "removal",
  },

  // === Land destruction package ===
  "Cleansing Wildfire": {
    cost: "{1}{R}",
    cmc: 2,
    type: "Sorcery",
    text: "Destroy target land. Its controller may search their library for a basic land card, put it onto the battlefield, then shuffle. Draw a card.",
    set: "ZNR",
    color: "R",
    role: "ld",
  },
  "Price of Freedom": {
    cost: "{1}{R}",
    cmc: 2,
    type: "Sorcery — Lesson",
    text: "Destroy target artifact or land an opponent controls. Its controller may search their library for a basic land card, put it onto the battlefield tapped, then shuffle. Draw a card.",
    set: "TLA",
    color: "R",
    role: "ld",
  },
  "Pillage": {
    cost: "{1}{R}",
    cmc: 2,
    type: "Sorcery",
    text: "Destroy target artifact or land. It can't be regenerated.",
    set: "ALL",
    color: "R",
    role: "ld",
  },

  // === Threats / engines ===
  "White Orchid Phantom": {
    cost: "{W}{W}",
    cmc: 2,
    type: "Creature — Spirit Knight",
    pt: "2/2",
    text: "Flying, first strike. When this creature enters, destroy up to one target nonbasic land. Its controller may search their library for a basic land card, put it onto the battlefield tapped, then shuffle.",
    set: "MH3",
    color: "W",
    role: "ld",
  },
  "Phlage, Titan of Fire's Fury": {
    cost: "{1}{R}{W}",
    cmc: 3,
    type: "Legendary Creature — Elder Giant",
    pt: "6/6",
    text: "When Phlage enters, sacrifice it unless it escaped. Whenever Phlage enters or attacks, it deals 3 damage to any target and you gain 3 life. Escape — {R}{R}{W}{W}, exile five other cards from your graveyard.",
    set: "MH3",
    color: "RW",
    role: "engine",
    rarity: "mythic",
  },
  "The Legend of Roku": {
    cost: "{2}{R}{R}",
    cmc: 4,
    type: "Enchantment — Saga",
    text: "I — Exile the top three cards of your library. Until the end of your next turn, you may play those cards. II — Add one mana of any color. III — Exile this Saga, then return it transformed under your control (Avatar Roku, firebending 4, {8}: 4/4 Dragon token).",
    set: "TLA",
    color: "R",
    role: "engine",
  },
  "Ephemerate": {
    cost: "{W}",
    cmc: 1,
    type: "Instant",
    text: "Exile target creature you control, then return it to the battlefield under its owner's control. Rebound.",
    set: "MH1",
    color: "W",
    role: "blink",
  },
  "Snapcaster Mage": {
    cost: "{1}{U}",
    cmc: 2,
    type: "Creature — Human Wizard",
    pt: "2/1",
    text: "Flash. When this creature enters, target instant or sorcery card in your graveyard gains flashback until end of turn. The flashback cost is equal to its mana cost.",
    set: "ISD",
    color: "U",
    role: "engine",
  },

  // === Lands ===
  "Sacred Foundry": { cost: "—", cmc: 0, type: "Land — Mountain Plains", text: "Shock land. {T}: Add {R} or {W}.", set: "RAV", color: "L", role: "land" },
  "Scalding Tarn": { cost: "—", cmc: 0, type: "Land", text: "{T}, Pay 1 life, Sacrifice: Search for an Island or Mountain card.", set: "ZEN", color: "L", role: "land" },
  "Arid Mesa": { cost: "—", cmc: 0, type: "Land", text: "{T}, Pay 1 life, Sacrifice: Search for a Mountain or Plains card.", set: "ZEN", color: "L", role: "land" },
  "Flooded Strand": { cost: "—", cmc: 0, type: "Land", text: "{T}, Pay 1 life, Sacrifice: Search for an Island or Plains card.", set: "ONS", color: "L", role: "land" },
  "Hallowed Fountain": { cost: "—", cmc: 0, type: "Land — Plains Island", text: "Shock land. {T}: Add {W} or {U}.", set: "DIS", color: "L", role: "land" },
  "Steam Vents": { cost: "—", cmc: 0, type: "Land — Island Mountain", text: "Shock land. {T}: Add {U} or {R}.", set: "GPT", color: "L", role: "land" },
  "Demolition Field": {
    cost: "—",
    cmc: 0,
    type: "Land",
    text: "{T}: Add {C}. {2}, {T}, Sacrifice this land: Destroy target nonbasic land an opponent controls if it has the same name as a land you control. That player may search their library for a basic land card, put it onto the battlefield, then shuffle.",
    set: "BRO",
    color: "L",
    role: "ld",
  },
  "Field of Ruin": {
    cost: "—",
    cmc: 0,
    type: "Land",
    text: "{T}: Add {C}. {1}, {T}, Sacrifice this land: Destroy target nonbasic land an opponent controls. Each player searches their library for a basic land card, puts it onto the battlefield, then shuffles.",
    set: "IMA",
    color: "L",
    role: "ld",
  },
  "Sunken Citadel": {
    cost: "—",
    cmc: 0,
    type: "Land",
    text: "Sunken Citadel enters tapped. As Sunken Citadel enters, choose a color. {T}: Add one mana of the chosen color. {T}: Add two mana of the chosen color. Spend this mana only to activate abilities of land sources.",
    set: "LCI",
    color: "L",
    role: "land",
  },
  "Cori Mountain Monastery": {
    cost: "—",
    cmc: 0,
    type: "Land",
    text: "This land enters tapped unless you control a Plains or an Island. {T}: Add {R}. {3}{R}, {T}: Exile the top card of your library. Until the end of your next turn, you may play that card.",
    set: "TDM",
    color: "L",
    role: "land",
  },
  "Eiganjo, Seat of the Empire": { cost: "—", cmc: 0, type: "Land — Plains", text: "Channel — {1}{W}, Discard: Destroy target nonbasic land.", set: "NEO", color: "L", role: "land" },
  "Otawara, Soaring City": { cost: "—", cmc: 0, type: "Land — Island", text: "Channel — {2}{U}, Discard: Bounce target nonland permanent.", set: "NEO", color: "L", role: "land" },
  "Sokenzan, Crucible of Defiance": { cost: "—", cmc: 0, type: "Land — Mountain", text: "Channel — {3}{R}: Create two 1/1 red Spirits with haste.", set: "NEO", color: "L", role: "land" },
  "Plains": { cost: "—", cmc: 0, type: "Basic Land — Plains", text: "{T}: Add {W}.", set: "BASIC", color: "L", role: "land" },
  "Island": { cost: "—", cmc: 0, type: "Basic Land — Island", text: "{T}: Add {U}.", set: "BASIC", color: "L", role: "land" },
  "Mountain": { cost: "—", cmc: 0, type: "Basic Land — Mountain", text: "{T}: Add {R}.", set: "BASIC", color: "L", role: "land" },

  // === Sideboard ===
  "Rest in Peace": { cost: "{1}{W}", cmc: 2, type: "Enchantment", text: "When this enters, exile all graveyards. If a card or token would be put into a graveyard from anywhere, exile it instead.", set: "RTR", color: "W", role: "hate" },
  "Surgical Extraction": { cost: "{B/P}", cmc: 1, type: "Instant", text: "Choose target card in a graveyard other than a basic land card. Search its owner's graveyard, hand, and library for any number of cards with the same name and exile them.", set: "NPH", color: "B", role: "hate" },
  "Celestial Purge": { cost: "{1}{W}", cmc: 2, type: "Instant", text: "Exile target black or red permanent.", set: "ARB", color: "W", role: "hate" },
  "Orim's Chant": { cost: "{W}", cmc: 1, type: "Instant", text: "Kicker {W}. Target player can't cast spells this turn. If this was kicked, creatures can't attack this turn.", set: "PLS", color: "W", role: "hate" },
  "High Noon": { cost: "{1}{W}", cmc: 2, type: "Enchantment", text: "Each player can't cast more than one spell each turn. {4}{R}, Sacrifice this enchantment: It deals 5 damage to any target.", set: "OTJ", color: "W", role: "hate" },
  "Kataki, War's Wage": { cost: "{1}{W}", cmc: 2, type: "Legendary Creature — Spirit", pt: "2/1", text: "All artifacts have 'At the beginning of your upkeep, sacrifice this artifact unless you pay {1}.'", set: "SOK", color: "W", role: "hate" },
  "Wear // Tear": { cost: "{1}{R} // {W}", cmc: 2, type: "Instant — Split", text: "Wear: Destroy target artifact. // Tear: Destroy target enchantment. Fuse.", set: "DGM", color: "RW", role: "hate" },
  "Vexing Bauble": { cost: "{0}", cmc: 0, type: "Artifact", text: "Spells your opponents cast that have no mana paid for them with mana cost cost {1} more. {3}, {T}, Sacrifice: Draw a card.", set: "MH3", color: "C", role: "hate" },
  "Anger of the Gods": { cost: "{1}{R}{R}", cmc: 3, type: "Sorcery", text: "Anger of the Gods deals 3 damage to each creature. Exile any creature that would die this turn.", set: "THS", color: "R", role: "hate" },
  "Stony Silence": { cost: "{1}{W}", cmc: 2, type: "Enchantment", text: "Activated abilities of artifacts can't be activated.", set: "ISD", color: "W", role: "hate" },
  "Engineered Explosives": { cost: "{X}", cmc: 0, type: "Artifact", text: "Sunburst. {2}, Sacrifice: Destroy each nonland permanent with mana value equal to the number of charge counters on this.", set: "MH1", color: "C", role: "hate" },
  "Mystical Dispute": { cost: "{1}{U}", cmc: 2, type: "Instant", text: "This spell costs {2} less to cast if it targets a blue spell. Counter target spell unless its controller pays {3}.", set: "ELD", color: "U", role: "counter" },
  "Negate": { cost: "{1}{U}", cmc: 2, type: "Instant", text: "Counter target noncreature spell.", set: "M11", color: "U", role: "counter" },
  "Disenchant": { cost: "{1}{W}", cmc: 2, type: "Instant", text: "Destroy target artifact or enchantment.", set: "M15", color: "W", role: "hate" },
  "Boil": { cost: "{2}{R}", cmc: 3, type: "Instant", text: "Destroy all Islands.", set: "8ED", color: "R", role: "hate" },
  "Blood Sun": { cost: "{1}{R}", cmc: 2, type: "Enchantment", text: "When this enters, draw a card. Lands have no abilities other than mana abilities.", set: "RIX", color: "R", role: "hate" },

  "Phelia, Exuberant Shepherd": {
    cost: "{1}{W}",
    cmc: 2,
    type: "Legendary Creature — Dog",
    pt: "2/2",
    text: "Flash. Whenever Phelia attacks, exile up to one other target nonland permanent. At the beginning of the next end step, return that card to the battlefield under its owner's control. If it entered under your control, put a +1/+1 counter on Phelia.",
    set: "MH3",
    color: "W",
    role: "blink",
    rarity: "mythic",
  },
  "Arena of Glory": {
    cost: "—",
    cmc: 0,
    type: "Land",
    text: "Arena of Glory enters tapped unless you control a Mountain. {R}, {T}, Exert this land: Add {R}{R}. If that mana is spent on a creature spell, it gains haste until end of turn.",
    set: "MH3",
    color: "L",
    role: "land",
  },
  "Consign to Memory": {
    cost: "{1}{U}",
    cmc: 2,
    type: "Instant",
    text: "Replicate {1}. Counter target triggered ability or colorless spell.",
    set: "MH3",
    color: "U",
    role: "counter",
  },
  "Teferi, Time Raveler": {
    cost: "{1}{W}{U}",
    cmc: 3,
    type: "Legendary Planeswalker — Teferi",
    text: "Each opponent can cast spells only any time they could cast a sorcery. +1: Until your next turn, you may cast sorcery spells as though they had flash. −3: Return up to one target artifact, creature, or enchantment to its owner's hand. Then draw a card.",
    set: "WAR",
    color: "WU",
    role: "engine",
  },
  "Slayers' Stronghold": {
    cost: "—",
    cmc: 0,
    type: "Land",
    text: "Slayers' Stronghold enters tapped. {T}: Add {C}. {2}{R}{W}, {T}: Target creature gets +2/+0 and gains vigilance and haste until end of turn.",
    set: "AVR",
    color: "L",
    role: "land",
  },


  // CONFIRMED: Flashback (Secrets of Strixhaven #115). 1-mana Snapcaster Mage.
  "Flashback": {
    cost: "{R}",
    cmc: 1,
    type: "Instant",
    text: "Target instant or sorcery card in your graveyard gains flashback until end of turn. The flashback cost is equal to its mana cost. (You may cast that card from your graveyard for its flashback cost. Then exile it.)",
    set: "SOS",
    color: "R",
    role: "engine",
  },
};
