// v6 — heavy revisions per feedback after studying babay23gg's 1st-place
// Jeskai Aggro list from Kazan Modern Championship 2026-04-25 (which runs
// 4 Quantum Riddler + 4 Phelia + 4 Phlage as the actual proven shell):
//   mtggoldfish.com/deck/7752675
//
// Feedback notes applied:
//  - "Phelia is a better card on its own than Solitude in some slots"
//  - "Phlage is super busted"
//  - "Look at sky blink decks"
//  - "Removal package is too dense (4 Erode + 4 Path + 3 Galvanic + 2 Wrath
//     of the Skies + 2 Solitude is too much)"
//  - "Ephemerate may be dead with too few targets — 2-3, not 4"
//  - "Drop Roku to 1-2"
//  - "Use the haste-land for Phlage" → Arena of Glory (MH3)
//  - "Manabase challenge: keep blue consistent despite Field of Ruin /
//     Demolition Field" → cut F.O.R. / Demolition counts in V1, keep them
//     in V3 where the engine is the win-con

const DECKS = {
  phlage_free_safe: {
    id: "phlage_free_safe",
    name: "PHLAGE-FREE SAFE (final)",
    subtitle: "Overnight final pick — score 63.70 ± 0.25",
    colors: "WUR",
    archetype: "Optimized-Final",
    pitch: "Locked overnight recommendation. Drops Phlage entirely (eliminates 22% Phlage-opening dead-card issue from Hybrid), bumps Snapcaster to 3, keeps 2 Wraths for sweepers. Hand-pattern data shows 1% better keep rate and 2.1% less color screw than Hybrid. Both within model noise but PF SAFE has cleaner opening hands.",
    gameplan: [
      "T1: Erode/Path on relevant 1-drop. Engine starts depleting.",
      "T2: Phelia (flash) or Phantom for engine pressure.",
      "T3: Wildfire/PoF on opp lands; Phelia attacks on next opportunity.",
      "T4: Wrath of the Skies for sweep, OR Snapcaster + flashback Wildfire.",
      "T5: Hardcast or warp Quantum Riddler. Phelia attack-blink for permanent.",
      "T6+: Solitude evoke as 5-mana exile + 3/2 lifelink, or Snapcaster reload.",
      "Win: aggressive Jeskai with depletion engine support and recurring flashback.",
    ],
    keyCombo: {
      name: "Phelia + Solitude + QR + Snapcaster",
      cards: ["Phelia, Exuberant Shepherd", "Solitude", "Quantum Riddler", "Snapcaster Mage"],
      desc: "Phelia attack-blinks Solitude for 2nd exile-removal trigger, OR blinks warped QR to make permanent. Snapcaster flashbacks Wildfire/PoF/Erode/Path from yard for repeat depletion. Four layered combos that all reinforce the WUR-blink-LD theme without recursive Phlage.",
    },
    mainboard: [
      ["White Orchid Phantom", 4],
      ["Quantum Riddler", 4],
      ["Phelia, Exuberant Shepherd", 2],
      ["Solitude", 2],
      ["Snapcaster Mage", 3],
      ["Erode", 4],
      ["Path to Exile", 4],
      ["Cleansing Wildfire", 4],
      ["Price of Freedom", 4],
      ["Galvanic Discharge", 2],
      ["Wrath of the Skies", 2],
      ["Arid Mesa", 4],
      ["Scalding Tarn", 4],
      ["Sacred Foundry", 4],
      ["Hallowed Fountain", 4],
      ["Steam Vents", 1],
      ["Arena of Glory", 1],
      ["Demolition Field", 1],
      ["Field of Ruin", 1],
      ["Misty Rainforest", 1],
      ["Plains", 2],
      ["Mountain", 1],
      ["Island", 1],
    ],
    sideboard: [
      ["Rest in Peace", 3],
      ["Celestial Purge", 2],
      ["Mystical Dispute", 2],
      ["Negate", 2],
      ["Surgical Extraction", 2],
      ["Consign to Memory", 2],
      ["High Noon", 1],
      ["Wrath of the Skies", 1],
    ],
    synergies: [
      ["Phelia, Exuberant Shepherd", "Solitude", "attack-blink → double exile-removal"],
      ["Phelia, Exuberant Shepherd", "Quantum Riddler", "attack-blink → permanent finisher"],
      ["Phelia, Exuberant Shepherd", "White Orchid Phantom", "blink → 2nd land kill"],
      ["Snapcaster Mage", "Cleansing Wildfire", "flashback → repeat basic-tutor"],
      ["Snapcaster Mage", "Erode", "flashback → repeat removal"],
      ["Snapcaster Mage", "Price of Freedom", "flashback → repeat LD-cantrip"],
      ["Erode", "White Orchid Phantom", "depletion engine: 8 forced basic-tutors"],
      ["Cleansing Wildfire", "Price of Freedom", "depletion-cantrip pair"],
      ["Path to Exile", "Erode", "1-mana removal pair"],
      ["Galvanic Discharge", "Wrath of the Skies", "energy stack for X-sweep"],
    ],
  },

  hybrid: {
    id: "hybrid",
    name: "HYBRID v19 (overnight FINAL)",
    subtitle: "Best-of-convergent hill-climbed build, score 63.49 ± 0.30",
    colors: "WUR",
    archetype: "Optimized-Final",
    pitch: "The locked overnight recommendation. Combines best swaps from 5 convergent hill-climb paths under the v19+ model with all corrections (phantom-shock fix, continuous shortfall, late-game scaling, manabase parity). 25 lands, 4 basics, 2-2-2 Phelia/Phlage/Solitude/Snapcaster pattern, 16 fetches+shocks for color smoothness, 3 LD-lands kept for engine support.",
    gameplan: [
      "T1: Erode/Path on relevant 1-drop. Basic search forced.",
      "T2: Phelia (flash hold-up) or Phantom (WW now reliable with 16 fetches+shocks).",
      "T3: Phlage hardcast {1RW} + Arena of Glory exert R = 9-damage haste swing OR Wildfire/PoF cantrip.",
      "T4: Wrath of the Skies for sweep, OR Snapcaster + flashback Wildfire from yard.",
      "T5: Hardcast or warp Quantum Riddler. Phelia attack-blink for permanent finisher.",
      "T6+: Engine has crippled opp lands. QR closes through the air.",
      "Win: aggressive Jeskai shell with depletion engine support.",
    ],
    keyCombo: {
      name: "Multi-axis convergent build",
      cards: ["Quantum Riddler", "Phelia, Exuberant Shepherd", "Solitude", "Snapcaster Mage"],
      desc: "Phelia attack-blinks Solitude for double exile-removal. Snapcaster flashbacks Wildfire/PoF for extra basic-tutors. QR warp+blink for permanent finisher. Three layered combos that all support the Jeskai-blink-LD theme.",
    },
    mainboard: [
      ["White Orchid Phantom", 4],
      ["Quantum Riddler", 4],
      ["Phelia, Exuberant Shepherd", 2],
      ["Phlage, Titan of Fire's Fury", 2],
      ["Solitude", 2],
      ["Snapcaster Mage", 2],
      ["Erode", 4],
      ["Path to Exile", 4],
      ["Cleansing Wildfire", 4],
      ["Price of Freedom", 4],
      ["Galvanic Discharge", 2],
      ["Wrath of the Skies", 1],
      ["Arid Mesa", 4],
      ["Scalding Tarn", 4],
      ["Sacred Foundry", 4],
      ["Hallowed Fountain", 4],
      ["Steam Vents", 1],
      ["Arena of Glory", 1],
      ["Demolition Field", 1],
      ["Field of Ruin", 2],
      ["Plains", 2],
      ["Mountain", 1],
      ["Island", 1],
    ],
    sideboard: [
      ["Rest in Peace", 3],
      ["Celestial Purge", 2],
      ["Mystical Dispute", 2],
      ["Negate", 2],
      ["Surgical Extraction", 2],
      ["Consign to Memory", 2],
      ["High Noon", 1],
      ["Wrath of the Skies", 1],
    ],
    synergies: [
      ["Phelia, Exuberant Shepherd", "Solitude", "attack-blink → double exile-removal"],
      ["Phelia, Exuberant Shepherd", "Quantum Riddler", "attack-blink → permanent finisher"],
      ["Phelia, Exuberant Shepherd", "White Orchid Phantom", "blink → 2nd non-basic kill"],
      ["Snapcaster Mage", "Cleansing Wildfire", "flashback for repeat basic-tutor"],
      ["Snapcaster Mage", "Erode", "flashback for repeat removal"],
      ["Snapcaster Mage", "Price of Freedom", "flashback for repeat LD-cantrip"],
      ["Erode", "White Orchid Phantom", "depletion engine: 8 forced basic-tutors"],
      ["Cleansing Wildfire", "Price of Freedom", "depletion-cantrip pair"],
      ["Path to Exile", "Erode", "1-mana removal pair"],
      ["Galvanic Discharge", "Wrath of the Skies", "energy stack"],
      ["Phlage, Titan of Fire's Fury", "Arena of Glory", "exert RR + haste → T3 attack for 9"],
      ["Field of Ruin", "Demolition Field", "non-basic kill + your-yard fuel"],
    ],
  },

  optimized: {
    id: "optimized",
    name: "Optimized v18",
    subtitle: "Phelia Riddler after 2-step hill-climb (composite 59.19)",
    colors: "WUR",
    archetype: "Optimized",
    pitch: "Final hill-climb output after v18 sim corrections (Solitude/Phelia combo, FoR/DF basic-count penalty, iterated Galvanic→Wrath energy via sim tracking, sigmoid depletion, conditional Sunken Citadel value). Adds 2 Solitude as Phelia attack-blink targets — repeated ETB exile-removal. Cuts 1 Phlage and 1 Phelia (legendary diminishing returns). Multi-seed verified: 8 seeds, mean 57.92, stdev 0.37.",
    gameplan: [
      "T1: Erode/Path on early threat → opp searches basic #1.",
      "T2: White Orchid Phantom (or Phelia flash-hold). Phantom destroys non-basic → basic #2.",
      "T2-3: Cleansing Wildfire / Price of Freedom on opp lands (cantrips), or self-Wildfire to fix mana.",
      "T3: Phlage hardcast {1}{R}{W} + Arena of Glory exert R for haste → 9 damage attack OR 3-damage trigger as Lightning Helix-equivalent + Phlage to yard.",
      "T4: Wrath of the Skies with X=banked-energy from Galvanic discharges → wide sweep.",
      "T4-5: Phelia flash-attack on Solitude or Quantum Riddler — Solitude blink = repeat exile-removal; QR blink = permanent finisher.",
      "T5+: Hardcast or warp Quantum Riddler. Engine has thinned opp basics.",
      "Win: 4/6 evasive QR finisher + recurring Phlage from yard + opp permanently at 1-2 lands.",
    ],
    keyCombo: {
      name: "Phelia + Solitude (insane per user feedback)",
      cards: ["Phelia, Exuberant Shepherd", "Solitude", "Quantum Riddler"],
      desc: "Phelia attacks → exile up to one nonland permanent (your own Solitude or QR). At next end step, returns under owner's control. Solitude's ETB exile-removal trigger fires AGAIN, hitting another opp creature. So Phelia attack with Solitude target = 2 creatures exiled minimum, plus +1/+1 counter on Phelia. With QR: Phelia turns the warped temporary QR into a permanent 4/6 flyer.",
    },
    mainboard: [
      ["White Orchid Phantom", 4],
      ["Phelia, Exuberant Shepherd", 2],
      ["Phlage, Titan of Fire's Fury", 2],
      ["Solitude", 2],
      ["Quantum Riddler", 4],
      ["Erode", 4],
      ["Path to Exile", 4],
      ["Galvanic Discharge", 2],
      ["Cleansing Wildfire", 4],
      ["Price of Freedom", 4],
      ["Wrath of the Skies", 2],
      ["Sacred Foundry", 3],
      ["Scalding Tarn", 4],
      ["Hallowed Fountain", 3],
      ["Arid Mesa", 4],
      ["Steam Vents", 1],
      ["Arena of Glory", 3],
      ["Field of Ruin", 3],
      ["Demolition Field", 2],
      ["Plains", 1],
      ["Mountain", 1],
      ["Island", 1],
    ],
    sideboard: [
      ["Rest in Peace", 3],
      ["Celestial Purge", 2],
      ["Mystical Dispute", 2],
      ["Negate", 2],
      ["Surgical Extraction", 2],
      ["Wrath of the Skies", 1],
      ["Consign to Memory", 2],
      ["High Noon", 1],
    ],
    synergies: [
      ["Phelia, Exuberant Shepherd", "Solitude", "attack-blink Solitude → exile second creature"],
      ["Phelia, Exuberant Shepherd", "Quantum Riddler", "warp + Phelia attack-blink → permanent finisher"],
      ["Phelia, Exuberant Shepherd", "White Orchid Phantom", "blink → 2nd non-basic kill"],
      ["Erode", "White Orchid Phantom", "depletion engine: 8 forced basic-tutors"],
      ["Cleansing Wildfire", "Price of Freedom", "depletion engine: 8 LD-cantrips"],
      ["Path to Exile", "Erode", "depletion engine: 8 1-mana removal"],
      ["Galvanic Discharge", "Wrath of the Skies", "energy stacking — banked E carries to Wrath X"],
      ["Phlage, Titan of Fire's Fury", "Arena of Glory", "exert R + haste → T3 attack for 9"],
      ["Phlage, Titan of Fire's Fury", "Cleansing Wildfire", "yard fuel for escape"],
      ["Demolition Field", "Field of Ruin", "6 free non-basic kills"],
    ],
  },


  source: {
    id: "source",
    name: "Source: Corkyboyy WR",
    subtitle: "Modern Challenge 64 2026-05-04, 13th place — unmodified reference",
    colors: "WR",
    archetype: "Reference list",
    isReference: true,
    pitch: "Corkyboyy's actual 13th-place WR list from the 2026-05-04 Modern Challenge 64 on MTGO (mtggoldfish.com/deck/7765976). No Quantum Riddler, no blue. The 1-of 'Flashback' is rendered as-is from the Goldfish data; identity uncertain.",
    gameplan: [
      "T1: Erode or Path on the relevant 1-drop. Opp searches basic #1.",
      "T2: White Orchid Phantom destroys a non-basic; opp searches basic #2.",
      "T2-3: Cleansing Wildfire / Price of Freedom on opp lands; cantrip into more LD. Basics #3-4.",
      "T3: Phlage hardcast as a clock (sac on ETB unless escaped).",
      "T4: Roku Chapter I — exile top 3, may play till next turn.",
      "T4-5: Wrath of the Skies on creature board for X=2 (sweeps 2-mv).",
      "T5+: Demolition Field / Field of Ruin break their last non-basics.",
      "Win: Phlage from yard (5-card escape), Avatar Roku tokens, Phantom beats.",
    ],
    keyCombo: {
      name: "Demolition Field + Sunken Citadel",
      cards: ["Demolition Field", "Sunken Citadel", "Cleansing Wildfire"],
      desc: "Sunken Citadel taps for 2 of any chosen color but spends only on land-source activated abilities. So a single Citadel powers Demolition Field's {2,T,sacrifice} alone. Cast Cleansing Wildfire on your spent Citadel to convert it into a basic + cantrip.",
    },
    mainboard: [
      ["White Orchid Phantom", 4],
      ["Phlage, Titan of Fire's Fury", 2],
      ["Solitude", 3],
      ["Erode", 4],
      ["Flashback", 1],
      ["Galvanic Discharge", 4],
      ["Path to Exile", 4],
      ["Cleansing Wildfire", 4],
      ["Price of Freedom", 4],
      ["Wrath of the Skies", 4],
      ["Wrath of God", 1],
      ["The Legend of Roku", 1],
      ["Cori Mountain Monastery", 3],
      ["Demolition Field", 4],
      ["Field of Ruin", 4],
      ["Mountain", 1],
      ["Plains", 5],
      ["Sacred Foundry", 4],
      ["Sunken Citadel", 3],
    ],
    sideboard: [
      ["Orim's Chant", 2],
      ["Vexing Bauble", 1],
      ["Celestial Purge", 2],
      ["High Noon", 3],
      ["Kataki, War's Wage", 2],
      ["Rest in Peace", 3],
      ["Wear // Tear", 1],
      ["The Legend of Roku", 1],
    ],
    synergies: [
      ["Erode", "White Orchid Phantom", "depletion engine"],
      ["Cleansing Wildfire", "Price of Freedom", "depletion engine"],
      ["Path to Exile", "Erode", "depletion engine"],
      ["Phlage, Titan of Fire's Fury", "Cleansing Wildfire", "yard fuel for escape"],
      ["The Legend of Roku", "Cori Mountain Monastery", "exile-play engines"],
      ["Demolition Field", "Sunken Citadel", "Citadel powers Demolition Field"],
      ["Demolition Field", "Field of Ruin", "8 free non-basic kills"],
      ["White Orchid Phantom", "Demolition Field", "redundant non-basic kill"],
    ],
  },

  phelia: {
    id: "phelia",
    name: "Phelia Riddler",
    subtitle: "Jeskai depletion + Phelia (3) + Phlage (3) + 4 QR",
    colors: "WUR",
    archetype: "Aggro-Blink",
    pitch: "Pivot toward the proven shell. babay23gg's 1st-place Kazan Modern Championship list runs **4 Quantum Riddler + 4 Phelia + 4 Phlage + Arena of Glory** — that's the model. I keep some depletion engine (4 Phantom + 4 Erode + 4 Wildfire + 4 Price of Freedom + 3 Path = 19 forced basic-tutors) but drop Solitude and Ephemerate per your feedback (too much removal, Ephemerate dead with few blink targets when Phelia handles the blinks via attacking). Cuts Demolition Field / Field of Ruin to 2 each so blue mana is reliable for hardcast QR.",
    gameplan: [
      "T1: Erode or Path on relevant 1-drop. Basic search #1.",
      "T2: White Orchid Phantom OR Phelia (flash, hold up for surprise blink) — basic #2.",
      "T3: Phlage hardcast for {1}{R}{W}; cast Arena of Glory's {R}, T, exert for {R}{R} → spent on Phlage = haste. Phlage attacks for 6 + 3 trigger = 9 damage on T3.",
      "T4: Phelia attacks → exile their best permanent until next end step. +1/+1 counter on Phelia. Galvanic Discharge or Erode on the rebuy.",
      "T5: Hardcast or warp Quantum Riddler. Phelia attacks targeting Riddler (yes — Phelia's exile-and-return makes QR permanent; Phelia's own +1/+1 counter triggers because QR returned under your control).",
      "T6+: 4/6 Riddler + Phelia (now 3/3 or 4/4) + recurring Phlage from yard via Arena of Glory + escape.",
      "Win: aggressive Jeskai clock; LD package is just a tempo tax, not the win-con.",
    ],
    keyCombo: {
      name: "Phelia + Arena of Glory + Phlage",
      cards: ["Phelia, Exuberant Shepherd", "Arena of Glory", "Phlage, Titan of Fire's Fury", "Quantum Riddler"],
      desc: "Phelia's attack-trigger exiles your own QR (cast via warp), returns it at end of turn as a NEW object — permanent finisher, just like Ephemerate but on a 2/2 flash body that grows. Arena of Glory's exert ({R}T → RR with haste-rider) is the haste enabler for Phlage on T3 hardcast or for Phlage escape on T5+. Same trick: spend the Arena R on Phlage to give it haste, immediate 3-damage trigger on attack.",
    },
    mainboard: [
      ["White Orchid Phantom", 4],
      ["Phelia, Exuberant Shepherd", 3],
      ["Phlage, Titan of Fire's Fury", 3],
      ["Quantum Riddler", 4],
      ["Erode", 4],
      ["Path to Exile", 2],
      ["Galvanic Discharge", 4],
      ["Cleansing Wildfire", 4],
      ["Price of Freedom", 4],
      ["Wrath of the Skies", 2],
      ["Scalding Tarn", 4],
      ["Arid Mesa", 4],
      ["Sacred Foundry", 2],
      ["Hallowed Fountain", 2],
      ["Steam Vents", 1],
      ["Arena of Glory", 3],
      ["Demolition Field", 4],
      ["Field of Ruin", 3],
      ["Plains", 1],
      ["Mountain", 1],
      ["Island", 1],
    ],
    sideboard: [
      ["Rest in Peace", 2],
      ["Celestial Purge", 2],
      ["Mystical Dispute", 2],
      ["Negate", 2],
      ["Surgical Extraction", 2],
      ["Wrath of the Skies", 2],
      ["Consign to Memory", 2],
      ["High Noon", 1],
    ],
    synergies: [
      ["Phelia, Exuberant Shepherd", "Quantum Riddler", "attack-blink → permanent finisher + Phelia counter"],
      ["Phelia, Exuberant Shepherd", "White Orchid Phantom", "blink → 2nd land kill, 2nd basic-tutor"],
      // (removed: Phelia→Phlage isn't a combo. Returned Phlage's 'sac unless escaped' trigger fires again, killing it.)
      ["Arena of Glory", "Phlage, Titan of Fire's Fury", "exert R produces RR-with-haste; Phlage attacks T3 for 9"],
      ["Erode", "White Orchid Phantom", "depletion (lighter package, 4+4 = 8 triggers)"],
      ["Cleansing Wildfire", "Price of Freedom", "depletion-cantrip pair"],
      ["Galvanic Discharge", "Wrath of the Skies", "energy synergy"],
      ["Quantum Riddler", "Arena of Glory", "exert R for hardcast helper (+haste irrelevant on QR but spell still casts)"],
    ],
  },

  pure: {
    id: "pure",
    name: "Pure Engine",
    subtitle: "No Phelia, no Ephemerate; vanilla 4 QR top-end",
    colors: "WR ·u",
    archetype: "Depletion-Vanilla",
    pitch: "Per your feedback the Wildfire variant was drifting toward Jeskai Blink without enough commitment. Killed it. This is the alternative you suggested: drop Solitude AND Ephemerate, just play Quantum Riddler as a vanilla top-end with no synergies. Maximum engine commitment (full 20 forced basic-tutors), Phlage at 4 (busted), 4 QR, 1 Roku as soft acceleration toward hardcast, Arena of Glory for Phlage haste. The simplest list to pilot. Probably the strongest depletion plan in pure win-rate vs. fair midrange decks.",
    gameplan: [
      "T1: Erode or Path; basic #1.",
      "T2: White Orchid Phantom destroys non-basic; basic #2.",
      "T2-3: Cleansing Wildfire / Price of Freedom on opp lands; cantrips into more LD. Basics #3-4.",
      "T3: Phlage hardcast + Arena of Glory exert (RR with haste-rider) → Phlage attacks for 9.",
      "T4-5: Engine continues. Roku Chapter I exiles 3 cards top of library, may play till next turn.",
      "T5-6: Roku Chapter II adds 1 mana of any color → with basic Island + 3 generic = {3}{U}{U} for hardcast Quantum Riddler.",
      "T6+: 4/6 flyer + Phlage clock. Engine has stripped opp basics by now.",
      "Win: long-game inevitability through depletion. QR is the body that closes; the engine is the strategy.",
    ],
    keyCombo: {
      name: "Roku II → Quantum Riddler hardcast",
      cards: ["The Legend of Roku", "Quantum Riddler", "Arena of Glory"],
      desc: "Roku ETB adds the chapter I trigger immediately (exile top 3 to play). Chapter II next upkeep: any color of mana — that's your blue source for hardcasting QR at 5. Arena of Glory does the same trick for Phlage's escape: exert R for RR; if spent on Phlage's creature spell it gains haste, attacks immediately for 6 + 3 trigger.",
    },
    mainboard: [
      ["White Orchid Phantom", 4],
      ["Phlage, Titan of Fire's Fury", 4],
      ["Quantum Riddler", 4],
      ["Erode", 4],
      ["Path to Exile", 3],
      ["Galvanic Discharge", 4],
      ["Cleansing Wildfire", 4],
      ["Price of Freedom", 4],
      ["Wrath of the Skies", 3],
      ["The Legend of Roku", 1],
      ["Sacred Foundry", 4],
      ["Hallowed Fountain", 2],
      ["Demolition Field", 3],
      ["Field of Ruin", 3],
      ["Sunken Citadel", 2],
      ["Arena of Glory", 3],
      ["Plains", 3],
      ["Mountain", 1],
      ["Island", 2],
      ["Eiganjo, Seat of the Empire", 1],
      ["Otawara, Soaring City", 1],
    ],
    sideboard: [
      ["Rest in Peace", 3],
      ["Celestial Purge", 2],
      ["High Noon", 2],
      ["Kataki, War's Wage", 2],
      ["Surgical Extraction", 2],
      ["Mystical Dispute", 2],
      ["Wear // Tear", 1],
      ["Consign to Memory", 1],
    ],
    synergies: [
      ["Phlage, Titan of Fire's Fury", "Arena of Glory", "exert RR + haste-rider → T3 attack for 9"],
      ["The Legend of Roku", "Quantum Riddler", "Chapter II adds U for hardcast"],
      ["Erode", "White Orchid Phantom", "depletion engine: 8 forced basic-tutors"],
      ["Cleansing Wildfire", "Price of Freedom", "depletion-cantrip pair"],
      ["Path to Exile", "Erode", "depletion-removal pair"],
      ["Phlage, Titan of Fire's Fury", "Cleansing Wildfire", "yard fuel for escape"],
      ["Demolition Field", "Field of Ruin", "6 free non-basic kills"],
      ["Demolition Field", "Sunken Citadel", "Citadel powers Demolition activation"],
      ["Galvanic Discharge", "Wrath of the Skies", "energy synergy"],
    ],
  },

  roku: {
    id: "roku",
    name: "Roku Hardcast",
    subtitle: "Engine + 3 Phlage + 2 Phelia + 4 QR + Arena of Glory",
    colors: "WR ·u",
    archetype: "Depletion-Stax",
    pitch: "Per your feedback this is the lead candidate. Adjusted: Phlage 4→3 (you said maybe 3); QR bumped 3→4 (you wanted 4); 2 Phelia for blink utility on Phlage and Phantom; 1 Roku as the soft U-fix. Full depletion engine intact. Arena of Glory for Phlage haste. Statistical sim shows this list has the best 'engine on T1-T2' availability (~73%) and the most consistent T3 Phlage hardcast (~21%); see the Stats panel for details.",
    gameplan: [
      "T1-2: Erode/Path/Wildfire/Phantom on every legal target. Basic #1-3 forced.",
      "T3: Phlage hardcast {1}{R}{W} + Arena of Glory exert {R}, T → RR-with-haste → Phlage attacks for 6 + 3 trigger = 9 damage on T3.",
      "T3-4: Phelia (flash) for surprise tempo; attack T4 for blink-Phantom or blink-Phlage repeat.",
      "T4-5: Roku enters; Chapter I exile-play 3 cards.",
      "T5: Roku Chapter II adds U → with basic Island + 3 generic = {3}{U}{U} for Quantum Riddler hardcast.",
      "T6+: Engine grinds opponent to 0 lands; QR + Phlage close.",
      "Win: long-game inevitability; not relying on the QR combo, just on basic-depletion + 4/6 fliers.",
    ],
    keyCombo: {
      name: "Arena of Glory + Phlage + Phelia",
      cards: ["Arena of Glory", "Phlage, Titan of Fire's Fury", "Phelia, Exuberant Shepherd"],
      desc: "Arena of Glory exerts to produce RR; if either R is spent on a creature spell, that creature gains haste. Hardcast Phlage T3 → RR from Arena → Phlage with haste attacks T3 for 6 + 3 trigger. Or escape Phlage T5 from yard ({R}{R}{W}{W}) — Arena's RR pays half the cost AND gives haste. Phelia's attack-trigger blinks Phlage for a re-ETB attack trigger (3 more damage + 3 more life).",
    },
    mainboard: [
      ["White Orchid Phantom", 4],
      ["Phlage, Titan of Fire's Fury", 3],
      ["Phelia, Exuberant Shepherd", 2],
      ["Quantum Riddler", 4],
      ["Erode", 4],
      ["Path to Exile", 4],
      ["Galvanic Discharge", 3],
      ["Cleansing Wildfire", 4],
      ["Price of Freedom", 4],
      ["Wrath of the Skies", 1],
      ["The Legend of Roku", 1],
      ["Sacred Foundry", 4],
      ["Hallowed Fountain", 2],
      ["Demolition Field", 4],
      ["Field of Ruin", 4],
      ["Sunken Citadel", 2],
      ["Arena of Glory", 3],
      ["Plains", 3],
      ["Mountain", 1],
      ["Island", 2],
      ["Eiganjo, Seat of the Empire", 1],
    ],
    sideboard: [
      ["Rest in Peace", 3],
      ["Celestial Purge", 2],
      ["High Noon", 2],
      ["Kataki, War's Wage", 2],
      ["Surgical Extraction", 2],
      ["Wear // Tear", 1],
      ["Mystical Dispute", 2],
      ["Consign to Memory", 1],
    ],
    synergies: [
      ["Phlage, Titan of Fire's Fury", "Arena of Glory", "RR + haste → T3 hardcast or T5 escape attack for 9"],
      // (removed: Phelia→Phlage doesn't loop — returned Phlage self-sacs again.)
      ["Phelia, Exuberant Shepherd", "White Orchid Phantom", "blink → 2nd non-basic kill"],
      ["The Legend of Roku", "Quantum Riddler", "Chapter II adds U for hardcast"],
      ["Erode", "White Orchid Phantom", "depletion engine: 8 forced basic-tutors"],
      ["Cleansing Wildfire", "Price of Freedom", "depletion-cantrip pair"],
      ["Path to Exile", "Erode", "depletion-removal pair"],
      ["Phlage, Titan of Fire's Fury", "Cleansing Wildfire", "yard fuel for escape"],
      ["Demolition Field", "Field of Ruin", "8 free non-basic kills"],
      ["Demolition Field", "Sunken Citadel", "Citadel powers Demolition activation"],
    ],
  },
};
